using System;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
#pragma warning disable 8618,0612
#nullable enable
namespace CdpClient.Cdp.Network;
/// <summary>
/// An object representing a report generated by the Reporting API.
/// </summary>
[Experimental]public sealed partial class ReportingApiReport {
[JsonPropertyName("id")]public ReportId Id{get;set;}
/// <summary>
/// The URL of the document that triggered the report.
/// </summary>
[JsonPropertyName("initiatorUrl")]public string InitiatorUrl{get;set;}
/// <summary>
/// The name of the endpoint group that should be used to deliver the report.
/// </summary>
[JsonPropertyName("destination")]public string Destination{get;set;}
/// <summary>
/// The type of the report (specifies the set of data that is contained in the report body).
/// </summary>
[JsonPropertyName("type")]public string Type{get;set;}
/// <summary>
/// When the report was generated.
/// </summary>
[JsonPropertyName("timestamp")]public Network.TimeSinceEpoch Timestamp{get;set;}
/// <summary>
/// How many uploads deep the related request was.
/// </summary>
[JsonPropertyName("depth")]public long Depth{get;set;}
/// <summary>
/// The number of delivery attempts made so far, not including an active attempt.
/// </summary>
[JsonPropertyName("completedAttempts")]public long CompletedAttempts{get;set;}
[JsonPropertyName("body")]public object Body{get;set;}
[JsonPropertyName("status")]public ReportStatus Status{get;set;}
}
